import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "@app/components/Navbar";
import Footer from "@app/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next App",
  applicationName: "Next.js",
  description: "Generated by create next app",
  keywords: ["Next.js", "React", "JavaScript"],
  creator: "Muhammad Rabi",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <main className="min-h-screen px-4 py-6 bg-slate-700 md:px-8 lg:px-24">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
