import "./globals.css";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="flex space-x-3 capitalize mb-5 cursor-pointer bg-slate-700 text-white p-3">
          <Link href="/">home</Link>
          <Link href="/posts">posts</Link>
          <Link href="/about">about</Link>
          <Link href="/profile">profile</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
